### ISSUE TITLE
Click checklist load (checklist + checklistgroup)

### ISSUE THREAD

**Issue by phuong-bui-88** [phuong-bui-88/task-react#5]
- [x] Click Checlist => Checklist + checklistGroup
- [x] [Unit test npm ](https://github.com/phuong-bui-88/docs/issues/1#issuecomment-1937784278)
- [x] [No content and catch](https://github.com/phuong-bui-88/docs/issues/1#issuecomment-1937777531)
- [x] [Is loading](https://github.com/phuong-bui-88/docs/issues/1#issuecomment-1937774249)

**Comment by phuong-bui-88** [comment]
![Image](https://github.com/phuong-bui-88/task-react/assets/1611646/5d88c917-b538-420b-9f48-56c52029fd2a)

**Comment by phuong-bui-88** [comment]
![Image](https://github.com/phuong-bui-88/task-react/assets/1611646/3842bd4c-1aa0-4d95-9cb2-843ca3cc50a4)

**Comment by phuong-bui-88** [comment]
![Image](https://github.com/phuong-bui-88/task-react/assets/1611646/36926371-e6e8-42a5-ab94-8fa828b9dfe2)

https://mhnpd.github.io/react-loader-spinner/docs/components/three-dots
Is loading

**Comment by phuong-bui-88** [comment]
https://playwright.dev/
